const keywords = ["one",
"two",
"three",
"four",
"five",
"six",
"seven",
"eight",
"nine",
"ten",
"eleven",
"twelve",
"thirteen",
"fourteen",
"fifteen",
"sixteen",
"seventeen",
"eighteen",
"nineteen",
"twenty",
"thirty",
"forty",
"fifty",
"sixty",
"seventy",
"eighty",
"ninety",
"hundred",
"thousand",
"a",
"a few",
"a couple",
"some",
"affirmative",
"yes",
"correct",
"right",
"sure",
"maybe",
"yup",
"definitely",
"certainly",
"negative",
"no",
"not",
"wrong",
"incorrect",
"nope",
"small",
"medium",
"large",
"easy",
"easy on the",
"light",
"extra",
"plus",
"minus",
"no",
"add",
"with",
"without",
"hold",
"hold the",
"burger", "burgers", "hamburger", "cheeseburger","hamburgers", "cheeseburgers", "double burger", "double cheeseburger",
"chicken", "chicken sandwich", "chiecken sandwiches", "chicken nugget", "chicken nuggets", "salad", "salads",
"french fries", "fries", "fry", "french", "chips",
"coke", "cokes", "sprite", "sprites", "diet",
"bun",
"buns",
"burger patty",
"burger patties",
"cheese",
"chicken patty",
"chicken patties",
"hamburger patty",
"hamburger patties",
"ice",
"ketchup",
"lettuce",
"mayo",
"mayonnaise",
"mustard",
"barbeque-sauce",
"onion",
"pickle",
"pickles",
"salt",
"sauce",
"sauces",
"What do you recommend",
"What would you recommend",
"Anything you'd recommend",
"Any recommendations",
"Do you have any recommendations",
"Can you make any recommendations"
]

module.exports = keywords;